name: pushtaka
description: "Aplikasi Manjemen Perpustakaan"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  dartz: ^0.10.1
  equatable: ^2.0.7
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  flutter_animate: ^4.5.2
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.2
  get_it: ^9.2.0
  skeletonizer: ^1.4.2
  introduction_screen: ^4.0.0
  flutter_dotenv: ^6.0.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon.png
    - assets/loading.gif

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

